-- ============================================================
-- Polytology — Supabase Schema
--
-- Run migrations in order from the /migrations folder:
--
--   001_initial_schema.sql    — strategies, trades, user_credentials
--   002_cached_markets.sql    — cached_markets (Gamma API cache)
--   003_strategies_eoa_address.sql — add eoa_address to strategies
--
-- Each file is idempotent (safe to re-run).
-- New changes should be added as a new numbered migration file,
-- not by editing an existing one.
-- ============================================================
